version: '3.6'
services:
  lb:
    container_name: lb
    image: gcr.io/coinos-326717/github.com/asoltys/caddy-cloudflare:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/coinos:/coinos
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy:/data
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      CLOUDFLARE_AUTH_TOKEN: "${CLOUDFLARE_AUTH_TOKEN}"
    networks:
      default:
        ipv4_address: 172.42.1.0
networks:
  default:
    name: net
    external: true
