version: '3.6'
services:
  caddy:
    container_name: caddy
    image: gcr.io/coinos-326717/github.com/asoltys/caddy-cloudflare:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/coinos:/coinos
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy:/data
    environment:
      CLOUDFLARE_AUTH_TOKEN: "${CLOUDFLARE_AUTH_TOKEN}"
    networks:
      default:
        ipv4_address: 172.42.1.0
  ci:
    container_name: ci
    build: .
    volumes:
      - .:/app
networks:
  default:
    name: net
    external: true
